### ISSUE TITLE
그리드 드래그가 되지 않음

### ISSUE THREAD

**Issue by scarf005** [Team-Snacks/frontend#20]
### 해결 가능 여부

- [ ] 지금 해결 가능

### 재현 방법

#12 이후로 테스트는 모두 통과하나 클릭시 드래그가 되지 않음

**Comment by jyhyun97** [comment]
일단 원인은 찾았습니다 handleDragMove에서 round함수가 제대로 동작하지 않는 게 문제였네요

**Comment by scarf005** [comment]
왠지 round 함수가 의심가기는 했었는데, 다시 한 번 확인해봐야겠네용

**Comment by jyhyun97** [comment]
헉.. 지금 다시 확인하니 아니었네요 제가 콘솔 로그를 잘못 찍어서 그랬읍니다.. cursorPosition을 찍어보려고 했는데 setCursorPosition을 찍어서 이상하게 나온 거였어요

**Comment by jyhyun97** [comment]
다시 찾아볼게요ㅠㅠ

**Comment by scarf005** [comment]
`neq` 문제인 것 같습니다, 한번 확인해볼게요

**Comment by jyhyun97** [comment]
Grid.tsx 25번 라인에서
`if (neq(cursorPosition, pos(0, 0)))`
조건문을 `cursorPosition !== pos(0, 0)` 로 바꿔보니 동작하네요
