### ISSUE TITLE
위젯 추가/삭제 구현

### ISSUE THREAD

**Issue by jyhyun97** [Team-Snacks/frontend#24]
### 상세 설명

- [x] 추가 : 스토어에서 위젯을 드래그 할 시 add-widget에 대한 api 데이터 생성
- [x] 삭제 : 스토어가 켜져 있을 때는 위젯 우측 상단에 x버튼을 생성하며, 클릭 시 delete-widget에 대한 api 데이터 생성

반영되는 걸 직접 화면으로 확인하려면 서버와 db가 필요할 것 같으니 일단은 데이터가 잘 생성되는지 테스트를 만드는 것으로 대신하겠습니다

### 노션 페이지

https://usanglee.notion.site/a400ce42792742259bf15cb7acd3b97c

**Comment by scarf005** [comment]
위젯 목록을 가져오고 수정하는 것을 인터페이스로 만들어서 테스트할때는 가짜 DB를 넣는 식으로 하면 될 것 같아요
예시)
```ts
type WidgetStore = {
	add: (widget: Widget) => void
	get: () => Widgets
}

**Comment by jyhyun97** [comment]
넵 한 번 그렇게 해볼게요
