### ISSUE TITLE
ladle grid에서 axios 오류

### ISSUE THREAD

**Issue by scarf005** [Team-Snacks/frontend#68]
### 해결 가능 여부

- [ ] 지금 해결 가능

### 재현 방법

`pnpm ladle serve` 이후 users/grid로 이동

![image](https://user-images.githubusercontent.com/54838975/208405564-06d03271-3d0a-4372-99bb-13826572f31e.png)

API 요청을 전부 사용해서 그런 것으로 보임

**Comment by jyhyun97** [comment]
ver1 close
