### ISSUE TITLE
회원가입시 CORS 오류

### ISSUE THREAD

**Issue by scarf005** [Team-Snacks/frontend#72]
### 해결 가능 여부

- [ ] 지금 해결 가능

### 재현 방법

1. 회원가입 페이지로 이동
2. 회원가입 정보 입력
3. CORS 오류 발생
![image](https://user-images.githubusercontent.com/54838975/209074408-aac36c80-6830-44cd-8606-c03354141388.png)

### 노션 페이지

https://www.notion.so/usanglee/CORS-9abb32bd4aeb4fae810aab82d5c42864

**Comment by jyhyun97** [comment]
ver1 close
